### ISSUE TITLE
Please don't bind to port 9000

### ISSUE THREAD

**Issue by lunaryorn** [proofit404/anaconda-mode#198]
Anaconda Mode seems to bind to port 9000 by default, unless it's already bound in which case it appears to try incrementally until it finds a free port.  This conflicts with the development server of Play which also binds to 9000 by default.  I can't change Play's port easily because all of our local development configuration relies on that port.

Is it possible for Anaconda to bind to a different port? It'd appear that there's already a way to communicate the port from the server to the client to make the aforementioned incrementation work so why not choose a random port instead?  Why don't you just bind to port 0 and let the OS pick a free port for you?

**Comment by proofit404** [comment]
Should be fixed in the anaconda-mode 0.1.5

**Comment by lunaryorn** [comment]
@proofit404 Awesome, thank you so much for fixing this issue so fast! Much appreciated!

If I update anaconda-mode from MELPA will it take care of updating service-factory as well, or do I need to do anything special?

**Comment by proofit404** [comment]
You don't need do anything special. Upgrade anaconda-mode from Melpa or Melpa-Stable and package will do the rest. Or at least tries to do that :)

**Comment by wohanley** [comment]
Does this interact with the port forwarding advice given in [the README|https://github.com/proofit404/anaconda-mode#vagrant]? If anaconda-mode's port isn't fixed, why forward 9000?

**Comment by proofit404** [comment]
No, now we need to figure out port number dynamically. README is outdated.

**Comment by wohanley** [comment]
Is there some documentation on working with Vagrant that is up to date?

**Comment by proofit404** [comment]
You can check `*anaconda-mode*` buffer to figure out port value. The rest of the process should be the same with README.

**Comment by wohanley** [comment]
I'm not sure how particular it is to the VirtualBox provider, but I know my Vagrant box needs a reboot to apply port forwards. I can't forward a port that I don't know about until anaconda-mode runs.

**Comment by proofit404** [comment]
Usually I do something like `ssh -nNT vagrant@localhost -p 2222 -L 9000:localhost:9000`.
