### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'environment' in service_factory

### ISSUE THREAD

**Issue by valignatev** [proofit404/anaconda-mode#296]
Just updated to 0.1.12 and got this error:
```python
127.0.0.1 - - [03/Jun/2018 02:31:24] ================================================================================
Traceback (most recent call last):
  File "/home/vj/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 81, in wrapper
TypeError: __init__() got an unexpected keyword argument 'environment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vj/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/vj/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/vj/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/vj/.emacs.d/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\\"__init__() got an unexpected keyword argument \'environment\'\\",)"}}')
```

**Comment by valignatev** [comment]
Downgrading to `0.1.11` and it's working, so something between these releases might've been broken

**Comment by proofit404** [comment]
Hi, can you provide more details about the virtual environment? Also, provide your emacs settings.

**Comment by valignatev** [comment]
Sure, for this one I don't use virtual environment, so it's my global python (which is 3.6.5, with jedi 0.12)
Emacs settings are these:
```emacs-lisp
(use-package anaconda-mode
  :hook ((python-mode . anaconda-mode)
         (python-mode . anaconda-eldoc-mode))
  :config
  (use-package company-anaconda
    :requires company
    :config (add-to-list 'company-backends 'company-anaconda)))
```
I'm using use-package, but it's basically the same as in readme

**Comment by valignatev** [comment]
Just looked it up, looks interesting. I'll try to debug it further and provide more details.

**Comment by proofit404** [comment]
Cool, thanks! Let me know if you need further assistance.

**Comment by valignatev** [comment]
Well, that's weird, I wanted to do a clean experiment and pruned `anaconda-mode` to set up 0.1.12 from scratch. And now it works, I can't reproduce the error myself again. So I'll guess I will close the issue, and maybe reopen if an error occurs again. ¯\_(ツ)_/¯

**Comment by diegotsu** [comment]
I have the same error here, did a clean up and it keeps the same, couldn't fix it

**Comment by proofit404** [comment]
Why do you need `json-rpc`?

**Comment by diegotsu** [comment]
I have the latest version of anaconda-mode installed fmo melpa in my Emacs set up. For some random reason I checked out v0.1.11 in another folder to try it. Back then there was a file called setup.py , I ran the command "python3 setup.py install", for some reason everything started working again.

Now my question is, I have latest version of anaconda-mode installed in my Emacs, but I ran the python installation script of v0.1.11, hehe did I mess up everything? Was it expected to start working again by running the "setup.py install"?

**Comment by valignatev** [comment]
@diegotsu Here comes the deps installation code: https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L98-L119
I guess at this point you'd better just prune anaconda-mode, install it from the beginning and try again :) Also, don't forget `.emacs.d/anaconda-mode` dir, it's the place when python dependencies go.

**Comment by proofit404** [comment]
Anaconda mode does not require setup.py anymore. It should handle all necessary information under the hood. Everything you need to do is install anaconda-mode from Melpa.

**Comment by psubnwell** [comment]
@proofit404 Hmmm... it's a magic command (for me) I heard from community, I'm not sure if `json-rpc` is necessary. 😅

**Comment by proofit404** [comment]
json-rpc dependency was removed in 2015. Feel free to uninstall it.

**Comment by NathanLovato** [comment]
Got the same error this morning, then checked https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L98-L119 -> the issue was jedi 0.11 was installed instead of the minimal 0.12 anaconda-mode requires. Fixed with

```shell
pip install --upgrade jedi
```

**Comment by proofit404** [comment]
`pip` completely fucked up in python homebrew installation for all MacOS users. 

Unfortunately, we can't use it.

If you can trick `easy_install` to upgrade packages during installation, please submit PR with version check.

**Comment by jaknel** [comment]
Thanks @NathanLovato 

Upgrading jedi from 0.10.2 to  0.12.1 resolved this issue for me.

**Comment by thnbp24** [comment]
I still have the exact same issue even with jedi 0.12.1. 
The error is gone if I disable anaconda-eldoc-mode.
I use the latest spacemacs and the python 3.5 and anaconda-mode 0.1.12.
Any idea? Thanks.

**Comment by thnbp24** [comment]
Thanks for quick reply. I just cleaned up the .emacs.d/.cache directory but the issue still exists.
I am inside virtual environment with all the dependencies described above installed.
The issue can be reproduced by downloading spacemacs and error would show on any python files.

Traceback (most recent call last):
  File "/home/jfk/.emacs.d/.cache/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/jfk/.emacs.d/.cache/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/jfk/.emacs.d/.cache/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/jfk/.emacs.d/.cache/anaconda-mode/0.1.12/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\\"__init__() got an unexpected keywo\
rd argument \'environment\'\\",)"}}')

**Comment by thnbp24** [comment]
The issue only happens with spacemacs. I don't have the issue with emacs prelude. It may have something to do with the configuration of spacemacs. I'll switch to emacs prelude then.

**Comment by valignatev** [comment]
@thnbp24 I tried it with spacemacs today and couldn't reproduce it. I wonder if it somehow uses an old version of jedi which it gathers from some deep and dark corners of your sys.path :)

Also interesting if https://github.com/proofit404/anaconda-mode/pull/327 could fix this issue for good.

**Comment by jingpengw** [comment]
I have the same issue in SpaceVim

**Comment by proofit404** [comment]
Hi @jingpengw

What what anaconda mode version do you use?

What python libraries it installed?

Regards, Artem.

**Comment by raphtoubi** [comment]
I have a similar problem. I've updated everything like said before but I still have this error 
Someone has an idea on how to deal with this error ?
<img width="619" alt="error" src="https://user-images.githubusercontent.com/43609010/55117427-1ddbee00-50eb-11e9-8f17-cb4a7a04e1ff.png">

**Comment by proofit404** [comment]
Anaconda-mode does not use uvicorn or click packages. You problem related to something else.

**Comment by raphtoubi** [comment]
@proofit404 could you tell me more about this ? My problem is related to what then ?

**Comment by proofit404** [comment]
You use issue tracker of the wrong project.
